image: node:14

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - publish

build:
  stage: build
  script:
    - yarn install
  artifacts:
    expire_in: 10 days
    paths:
      - node_modules/

unit-test:
  stage: test
  script:
    - yarn test

publish:
  image: electronuserland/builder:wine
  stage: publish
  artifacts:
    expire_in: 10 days
    paths:
      - release/
  before_script:
    - yarn rebuild node-sass
  allow_failure: false
  script:
    - yarn package-all
  only:
    - master
    - dev
  when: manual
